Java version, Gradle and Gradle Plugin updates
mooziii/snipping-tool-fix pull request #1
Opened 2023-03-03 19:32 UTC by DinoMarlir

- Java release: 16 -> 17
- Kotlin JVM: 1.7.20 -> 1.8.10

*NEW VERSION*
1.0.0 -> 1.0.1

2023-03-03 19:33 UTC, DinoMarlir commented
@mooziii should I remove the OptIn annontation over the main function?

2023-03-03 19:34 UTC, mooziii commented
nein ich release jetzt kein update nur wegen version bumps vergiss es

2023-03-03 19:36 UTC, iswearimmrtobi commented
würd mir stinken

2023-03-03 19:37 UTC, DinoMarlir commented
@iswearimmrtobi why?

2023-03-03 19:37 UTC, mooziii commented
das ist der größte contributions farmen moment

2023-03-03 19:38 UTC, DinoMarlir commented
@mooziii i wanted to help you to keep your versions up to date, there is no reason to react agressive.

2023-03-03 19:39 UTC, iswearimmrtobi commented
wenn ich eine Flasche so fest zudrehe, dass ich sie nicht mehr öffnen kann. Bin ich dann stark oder schwach?

2023-03-03 19:39 UTC, DinoMarlir commented
@iswearimmrtobi I don't understand what you mean...

2023-03-03 19:44 UTC, DinoMarlir commented
@mooz where is the problem with my contribution? What can I improve?

2023-03-03 19:45 UTC, mooziii commented
1. I don't see a reason to update this anymore as it does what it should and if there is no new feature, bug fix or whatever I won't release an update for it / merge the PR as I'm not going to touch this ever again
2. Why would you bump the java version? There is absolutely no reason for this upgrade as it only makes some systems incompatible

2023-03-03 19:47 UTC, mooziii commented
3. On Windows 11 systems the issue seems to be fixed and I'm expecting Microsoft to fix this in Windows 10 too (maybe 23H1? Idk)

2023-03-03 19:49 UTC, DinoMarlir commented
@mooziii I changed the Java version in the `build.gradle.kts` file because Java 16 is not a Java LTS version and support ended on 6 Mar 2021 and no longer receives updates.

2023-03-03 19:51 UTC, mooziii commented
yeah but what has this to do with the jdk version the jar was built with? Actually I wanted to use java 8 but due to some kotlin features only being available for java 16 I choose to use 16 back then

2023-03-03 19:52 UTC, DinoMarlir commented
@mooziii I can change the java version back to 16 if you want.

2023-03-03 19:53 UTC, DinoMarlir commented
What type of feature do you want to have in 'snipping tool fix'? Maybe a autofix that automatically kills the task?

2023-03-03 19:55 UTC, mooziii commented
I already thought of an autokill feature but the problem there is that you won't be able to take screenshots at all if the tasks gets killed instantly

2023-03-03 19:56 UTC, DinoMarlir commented
Maybe we could do that with a delay.

2023-03-03 19:57 UTC, DinoMarlir commented
Oh the task starts when you press the hotkey, right?

2023-03-03 19:57 UTC, mooziii commented
> Oh the task starts when you press the hotkey, right?
yes, this feature would only be great if you can detect if the screenshot was taken or not

2023-03-03 19:58 UTC, DinoMarlir commented
Isn't there a way to see if the menu has been closed (e.g. if something goes to the clipboard)?

2023-03-03 19:59 UTC, mooziii requested changes

2023-03-03 19:59 UTC, mooziii commented on build.gradle.kts
> +        options.release.set(17)
Change this back to 16 (maybe try 11?)

2023-03-03 19:59 UTC, mooziii commented on build.gradle.kts
> +version = "1.0.1"
Please remove this version bump if no new features will be added

2023-03-03 20:00 UTC, DinoMarlir commented on build.gradle.kts
> +        options.release.set(17)
👍

2023-03-03 20:08 UTC, DinoMarlir commented on build.gradle.kts
> +        options.release.set(17)
I changed it to `11`

2023-03-03 20:12 UTC, mooziii commented on src/main/kotlin/me/obsilabor/snippingtoolfix/SnippingToolFix.kt
> +import kotlin.streams.toList
?

2023-03-03 21:08 UTC, DinoMarlir commented on src/main/kotlin/me/obsilabor/snippingtoolfix/SnippingToolFix.kt
> +import kotlin.streams.toList
The toList function has to be imported in Java 11.

2023-03-11 14:42 UTC, mooziii commented
so Kollege Schnürschuh wie siehts aus

2023-03-11 16:46 UTC, DinoMarlir commented
What type of feature do you want to have?

2023-03-11 16:48 UTC, closed without merging